#!/bin/ash

cd /var/www && composer install --optimize-autoloader --no-scripts --no-dev --no-suggest

sleep 15

echo Filling the queue with messages

cd /var/www && bin/send_messages
cd /var/www && bin/console messenger:consume
