#!/usr/bin/env php
<?php

declare(strict_types = 1);

use App\StoreCustomerCommand;
use function ServiceBus\Common\uuid;
use Amp\Loop;

include __DIR__ . '/../vendor/autoload.php';

$interactions = new \DemoPublisher(__DIR__ . '/../.env');

Loop::run(
    static function() use ($interactions): \Generator
    {
        try
        {
            for($i = 0; $i < 100000; $i++)
            {
                yield $interactions->sendMessage(
                    new StoreCustomerCommand(uuid(), 'name_' . $i, 'name@qwerty.root')
                );
            }
        }
        catch(Throwable $throwable)
        {
            echo $throwable->getMessage(), \PHP_EOL;
        }

        Loop::stop();
    }
);

unset($interactions);

echo 'Filling in the message queue is completed', \PHP_EOL;