#!/usr/bin/env php
<?php

declare(strict_types = 1);

use App\StoreCustomerCommand;
use function Desperado\ServiceBus\Common\uuid;

include __DIR__ . '/../vendor/autoload.php';

$interactions = new DemoPublisher(__DIR__ . '/../.env');

\Amp\Promise\wait(
    \Amp\call(
        static function() use ($interactions): \Generator
        {
            for($i = 0; $i < 100000; $i++)
            {
                yield $interactions->sendMessage(
                    new StoreCustomerCommand(uuid(), 'name_' . $i, 'name@qwerty.root')
                );
            }
        }
    )
);
