#!/usr/bin/env php
<?php

declare(strict_types = 1);

use App\StoreCustomerCommand;
use function ServiceBus\Common\uuid;
use function Amp\Promise\wait;
use function Amp\call;

include __DIR__ . '/../vendor/autoload.php';

$interactions = new \DemoPublisher(__DIR__ . '/../.env');

wait(
    call(
        static function() use ($interactions): \Generator
        {
            for($i = 0; $i < 100000; $i++)
            {
                yield $interactions->sendMessage(
                    new StoreCustomerCommand(uuid(), 'name_' . $i, 'name@qwerty.root')
                );
            }
        }
    )
);
