#!/bin/ash

cd /var/www && composer install --optimize-autoloader --no-scripts --no-dev --no-suggest

sleep 15

echo Filling the queue with messages
cd /var/www && tools/send_messages

/var/www/bin/consumer
